apiVersion: apps/v1
kind: Deployment
metadata:
  name: yt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yt
  template:
    metadata:
      labels:
        app: yt
    spec:
      containers:
      - image: pereceh/yt:node
        name: yt

---

apiVersion: v1
kind: Service
metadata:
  name: yt
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "yt"
    port: 3000
  selector:
    app: yt
